import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  societies: defineTable({
    name: v.string(),
    address: v.optional(v.string()),
    city: v.optional(v.string()),
    totalFlats: v.optional(v.number()),
    totalBlocks: v.optional(v.number()),
    subscriptionPlan: v.optional(v.string()),
    isActive: v.optional(v.boolean()),
    mrr: v.optional(v.number()),
    helplinePhone: v.optional(v.string()),
    upiId: v.optional(v.string()),
    createdAt: v.optional(v.number()),
  }),

  blocks: defineTable({
    societyId: v.id("societies"),
    name: v.string(),
    type: v.optional(v.string()),
    totalFlats: v.optional(v.number()),
    occupiedFlats: v.optional(v.number()),
    createdAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  waterTanks: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    name: v.string(),
    type: v.optional(v.string()),
    capacityKL: v.optional(v.number()),
    currentLevelPct: v.optional(v.number()),
    lastUpdated: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  users: defineTable({
    tokenIdentifier: v.optional(v.string()),
    name: v.optional(v.string()),
    email: v.optional(v.string()),
    phone: v.optional(v.string()),
    role: v.optional(v.string()),
    societyId: v.optional(v.id("societies")),
    blockId: v.optional(v.id("blocks")),
    defaultBlockId: v.optional(v.id("blocks")),
    flatNumber: v.optional(v.string()),
    flatType: v.optional(v.string()),
    isActive: v.optional(v.boolean()),
    isAnonymous: v.optional(v.boolean()),
    moveInDate: v.optional(v.number()),
    notifInApp: v.optional(v.boolean()),
    notifWhatsapp: v.optional(v.boolean()),
    onboardingComplete: v.optional(v.boolean()),
    createdAt: v.optional(v.number()),
  })
    .index("by_token", ["tokenIdentifier"])
    .index("by_society", ["societyId"]),

  staff: defineTable({
    societyId: v.id("societies"),
    name: v.string(),
    role: v.optional(v.string()),
    phone: v.optional(v.string()),
    shift: v.optional(v.string()),
    isOnDuty: v.optional(v.boolean()),
    lastAttendanceAt: v.optional(v.number()),
    createdAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  vendors: defineTable({
    societyId: v.id("societies"),
    name: v.string(),
    type: v.optional(v.string()),
    phone: v.optional(v.string()),
    whatsapp: v.optional(v.string()),
    ratePerUnit: v.optional(v.number()),
    unit: v.optional(v.string()),
    isPreferred: v.optional(v.boolean()),
    isActive: v.optional(v.boolean()),
    rating: v.optional(v.number()),
    totalJobs: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  dgUnits: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    name: v.string(),
    capacityKVA: v.optional(v.number()),
    dieselCapacityLiters: v.optional(v.number()),
    dieselLevelLiters: v.optional(v.number()),
    isRunning: v.optional(v.boolean()),
    totalRuntimeHours: v.optional(v.number()),
    consumptionRateLPH: v.optional(v.number()),
    lastServiceDate: v.optional(v.number()),
    lastUpdated: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  maintenanceCharges: defineTable({
    societyId: v.id("societies"),
    flatType: v.optional(v.string()),
    monthlyAmount: v.optional(v.number()),
    dueDay: v.optional(v.number()),
    lateFeeAmount: v.optional(v.number()),
    lateFeeType: v.optional(v.string()),
    effectiveFrom: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  payments: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    residentId: v.optional(v.id("users")),
    type: v.optional(v.string()),
    description: v.optional(v.string()),
    amount: v.optional(v.number()),
    dueDate: v.optional(v.number()),
    status: v.optional(v.string()),
    paidAt: v.optional(v.number()),
    paymentMethod: v.optional(v.string()),
    confirmedBy: v.optional(v.id("users")),
    createdAt: v.optional(v.number()),
  })
    .index("by_society", ["societyId"])
    .index("by_resident", ["residentId"]),

  serviceRequests: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    residentId: v.optional(v.id("users")),
    category: v.optional(v.string()),
    description: v.optional(v.string()),
    priority: v.optional(v.string()),
    status: v.optional(v.string()),
    assignedTo: v.optional(v.id("users")),
    resolvedAt: v.optional(v.number()),
    residentRating: v.optional(v.number()),
    createdAt: v.optional(v.number()),
  })
    .index("by_society", ["societyId"])
    .index("by_resident", ["residentId"]),

  broadcasts: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    sentBy: v.optional(v.id("users")),
    title: v.optional(v.string()),
    message: v.optional(v.string()),
    type: v.optional(v.string()),
    targetAudience: v.optional(v.string()),
    channels: v.optional(v.array(v.string())),
    sentCount: v.optional(v.number()),
    deliveredCount: v.optional(v.number()),
    sentAt: v.optional(v.number()),
    createdAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  notices: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    title: v.optional(v.string()),
    content: v.optional(v.string()),
    type: v.optional(v.string()),
    postedBy: v.optional(v.id("users")),
    isPinned: v.optional(v.boolean()),
    expiresAt: v.optional(v.number()),
    createdAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  adminTickets: defineTable({
    societyId: v.optional(v.id("societies")),
    raisedBy: v.optional(v.id("users")),
    subject: v.optional(v.string()),
    category: v.optional(v.string()),
    description: v.optional(v.string()),
    priority: v.optional(v.string()),
    status: v.optional(v.string()),
    resolvedAt: v.optional(v.number()),
    createdAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  alerts: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    utility: v.optional(v.string()),
    alertType: v.optional(v.string()),
    severity: v.optional(v.string()),
    title: v.optional(v.string()),
    message: v.optional(v.string()),
    isResolved: v.optional(v.boolean()),
    resolvedBy: v.optional(v.id("users")),
    resolvedAt: v.optional(v.number()),
    triggeredAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  waterReadings: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    source: v.optional(v.string()),
    readingType: v.optional(v.string()),
    value: v.optional(v.number()),
    unit: v.optional(v.string()),
    recordedBy: v.optional(v.id("users")),
    recordedAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  powerReadings: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    source: v.optional(v.string()),
    readingType: v.optional(v.string()),
    valueKWH: v.optional(v.number()),
    recordedBy: v.optional(v.id("users")),
    recordedAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  sewageReadings: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    stpStatus: v.optional(v.string()),
    sludgeTankPct: v.optional(v.number()),
    treatedTankPct: v.optional(v.number()),
    inflowRateLPH: v.optional(v.number()),
    recordedBy: v.optional(v.id("users")),
    recordedAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  wasteLogs: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    dryWasteKG: v.optional(v.number()),
    wetWasteKG: v.optional(v.number()),
    totalKG: v.optional(v.number()),
    segregationOk: v.optional(v.boolean()),
    loggedBy: v.optional(v.id("users")),
    loggedAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  gasReadings: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    meterReading: v.optional(v.number()),
    consumptionSCM: v.optional(v.number()),
    pressurePSI: v.optional(v.number()),
    recordedBy: v.optional(v.id("users")),
    recordedAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  garbageCollectionLog: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    scheduledAt: v.optional(v.number()),
    collectedAt: v.optional(v.number()),
    status: v.optional(v.string()),
    vendorId: v.optional(v.id("vendors")),
    confirmedBy: v.optional(v.id("users")),
  }).index("by_society", ["societyId"]),

  powerOutages: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    dgUnitId: v.optional(v.id("dgUnits")),
    startedAt: v.optional(v.number()),
    endedAt: v.optional(v.number()),
    durationHrs: v.optional(v.number()),
    dieselUsedL: v.optional(v.number()),
    loggedBy: v.optional(v.id("users")),
  }).index("by_society", ["societyId"]),

  tankerOrders: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    vendorId: v.optional(v.id("vendors")),
    quantityKL: v.optional(v.number()),
    status: v.optional(v.string()),
    orderedBy: v.optional(v.id("users")),
    triggeredBy: v.optional(v.string()),
    scheduledAt: v.optional(v.number()),
    deliveredAt: v.optional(v.number()),
    cost: v.optional(v.number()),
    createdAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  predictionLog: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    utility: v.optional(v.string()),
    predictionType: v.optional(v.string()),
    predictedValue: v.optional(v.number()),
    predictedAt: v.optional(v.number()),
    eventDate: v.optional(v.number()),
    confidenceScore: v.optional(v.number()),
    actualValue: v.optional(v.number()),
    wasAccurate: v.optional(v.boolean()),
    modelVersion: v.optional(v.string()),
  }).index("by_society", ["societyId"]),

  shifts: defineTable({
    societyId: v.id("societies"),
    staffId: v.optional(v.id("staff")),
    blockId: v.optional(v.id("blocks")),
    date: v.optional(v.number()),
    shiftType: v.optional(v.string()),
    startTime: v.optional(v.string()),
    endTime: v.optional(v.string()),
    status: v.optional(v.string()),
    markedBy: v.optional(v.id("users")),
    markedAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  visitors: defineTable({
    societyId: v.id("societies"),
    registeredBy: v.id("users"),
    visitorName: v.string(),
    visitorPhone: v.string(),
    expectedAt: v.number(),
    passCode: v.string(),
    checkedInAt: v.optional(v.number()),
    checkedOutAt: v.optional(v.number()),
    gatepassSent: v.optional(v.boolean()),
    purposeFlat: v.optional(v.string()),
    vehicleNumber: v.optional(v.string()),
    createdAt: v.number(),
  })
    .index("by_society", ["societyId"])
    .index("by_resident", ["registeredBy"])
    .index("by_pass_code", ["passCode"]),

  vehicles: defineTable({
    societyId: v.id("societies"),
    residentId: v.optional(v.id("users")),
    vehicleNumber: v.optional(v.string()),
    type: v.optional(v.string()),
    parkingSlot: v.optional(v.string()),
    createdAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),

  tasks: defineTable({
    societyId: v.id("societies"),
    blockId: v.optional(v.id("blocks")),
    title: v.optional(v.string()),
    description: v.optional(v.string()),
    priority: v.optional(v.string()),
    status: v.optional(v.string()),
    assignedTo: v.optional(v.id("users")),
    createdBy: v.optional(v.id("users")),
    createdAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    dueAt: v.optional(v.number()),
  }).index("by_society", ["societyId"]),
});
