"use client";

import { useQuery } from "convex/react";
import { api } from "@/convex/_generated/api";
import { useActiveBlock } from "@/hooks/use-active-block";
import { useState } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { BarChart3, Download, Loader2 } from "lucide-react";
import { toast } from "sonner";

const MONTHS = [
  "January","February","March","April","May","June",
  "July","August","September","October","November","December",
];

export default function ReportsPage() {
  const profile = useQuery(api.users.getMyProfile);
  const { blockId } = useActiveBlock(profile?.defaultBlockId);
  const societyId = profile?.societyId;

  const now = new Date();
  const [year, setYear] = useState(now.getFullYear());
  const [month, setMonth] = useState(now.getMonth() + 1);
  const [exporting, setExporting] = useState(false);

  const skip = !(societyId && blockId);
  const args = skip ? ("skip" as const) : { societyId, blockId, year, month };

  const waterSummary = useQuery(api.reports.getMonthlyWaterSummary, args);
  const powerSummary = useQuery(api.reports.getMonthlyPowerSummary, args);
  const wasteSummary = useQuery(api.reports.getMonthlyWasteSummary, args);
  const gasSummary = useQuery(api.reports.getMonthlyGasSummary, args);
  const sewageSummary = useQuery(api.reports.getMonthlySewageSummary, args);

  async function handleExport() {
    if (typeof window === "undefined") return;
    setExporting(true);
    try {
      const { default: jsPDF } = await import("jspdf");
      const { default: autoTable } = await import("jspdf-autotable");
      const doc = new jsPDF();
      const monthLabel = `${MONTHS[month - 1]} ${year}`;

      // Header
      doc.setFillColor(15, 110, 86);
      doc.rect(0, 0, 210, 28, "F");
      doc.setTextColor(255, 255, 255);
      doc.setFontSize(18);
      doc.setFont("helvetica", "bold");
      doc.text("BlockSense Monthly Report", 14, 13);
      doc.setFontSize(11);
      doc.setFont("helvetica", "normal");
      doc.text(monthLabel, 14, 22);
      doc.setTextColor(26, 26, 26);

      let y = 38;

      const addSection = (
        title: string,
        body: [string, string][],
        color: [number, number, number]
      ) => {
        doc.setFontSize(12);
        doc.setFont("helvetica", "bold");
        doc.setTextColor(...color);
        doc.text(title, 14, y);
        doc.setTextColor(26, 26, 26);
        y += 5;
        autoTable(doc, {
          startY: y,
          head: [["Metric", "Value"]],
          body,
          theme: "grid",
          styles: { fontSize: 9, font: "helvetica" },
          headStyles: { fillColor: color, textColor: [255, 255, 255] },
        });
        y = (doc as any).lastAutoTable.finalY + 10;
      };

      if (waterSummary) {
        addSection("Water", [
          ["Total consumption", `${waterSummary.totalConsumptionKL} KL`],
          ["Tanker orders", String(waterSummary.tankerCount)],
          ["Tanker volume", `${waterSummary.tankerKL} KL`],
          ["Tanker cost", `₹${waterSummary.tankerCost.toLocaleString()}`],
        ], [24, 95, 165]);
      }

      if (powerSummary) {
        addSection("Power", [
          ["Total consumption", `${powerSummary.totalConsumptionKWH} kWh`],
          ["Outages", String(powerSummary.outageCount)],
          ["Outage hours", `${powerSummary.totalOutageHrs.toFixed(1)} h`],
          ["Diesel used", `${powerSummary.totalDieselUsedL.toFixed(1)} L`],
        ], [133, 79, 11]);
      }

      if (gasSummary) {
        addSection("Gas", [
          ["Total consumption", `${gasSummary.totalConsumptionSCM} SCM`],
          ["Avg pressure", `${gasSummary.avgPressurePSI} PSI`],
          ["Readings recorded", String(gasSummary.readings)],
          ["Last meter reading", String(gasSummary.lastMeterReading)],
        ], [15, 110, 86]);
      }

      if (sewageSummary) {
        addSection("Sewage / STP", [
          ["Readings logged", String(sewageSummary.readings)],
          ["Normal uptime", `${sewageSummary.uptimePct}%`],
          ["Avg sludge level", `${sewageSummary.avgSludgePct}%`],
        ], [153, 60, 29]);
      }

      if (wasteSummary) {
        addSection("Waste", [
          ["Total waste", `${wasteSummary.totalKG} KG`],
          ["Dry waste", `${wasteSummary.dryKG} KG`],
          ["Wet waste", `${wasteSummary.wetKG} KG`],
          ["Segregation compliance", `${wasteSummary.segregationCompliance}%`],
        ], [153, 53, 86]);
      }

      // Footer
      doc.setFontSize(8);
      doc.setTextColor(150);
      doc.text(
        `Generated by BlockSense on ${new Date().toLocaleDateString("en-IN")}`,
        14,
        doc.internal.pageSize.height - 8
      );

      doc.save(`blocksense-${year}-${String(month).padStart(2, "0")}.pdf`);
      toast.success("PDF exported");
    } catch (e) {
      toast.error("Failed to export PDF");
    } finally {
      setExporting(false);
    }
  }

  return (
    <div className="space-y-5">
      <div className="flex items-center justify-between flex-wrap gap-3">
        <h1 className="text-lg font-bold flex items-center gap-2">
          <BarChart3 className="h-5 w-5" />
          Monthly Reports
        </h1>
        <div className="flex items-center gap-2">
          <Select value={String(month)} onValueChange={(v) => setMonth(Number(v))}>
            <SelectTrigger className="w-36"><SelectValue /></SelectTrigger>
            <SelectContent>
              {MONTHS.map((m, i) => (
                <SelectItem key={i} value={String(i + 1)}>{m}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Select value={String(year)} onValueChange={(v) => setYear(Number(v))}>
            <SelectTrigger className="w-24"><SelectValue /></SelectTrigger>
            <SelectContent>
              {[2024, 2025, 2026].map((y) => (
                <SelectItem key={y} value={String(y)}>{y}</SelectItem>
              ))}
            </SelectContent>
          </Select>
          <Button size="sm" onClick={handleExport} disabled={exporting || skip}>
            {exporting
              ? <Loader2 className="mr-2 h-3.5 w-3.5 animate-spin" />
              : <Download className="mr-2 h-3.5 w-3.5" />}
            Export PDF
          </Button>
        </div>
      </div>

      <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-3 gap-4">
        {/* Water */}
        <Card>
          <CardHeader>
            <CardTitle className="text-sm" style={{ color: "#185FA5" }}>Water</CardTitle>
          </CardHeader>
          <CardContent>
            {!waterSummary
              ? <p className="text-sm text-muted-foreground">Loading…</p>
              : (
                <dl className="space-y-2 text-sm">
                  <ReportRow label="Total consumption" value={`${waterSummary.totalConsumptionKL} KL`} />
                  <ReportRow label="Tanker orders" value={String(waterSummary.tankerCount)} />
                  <ReportRow label="Tanker volume" value={`${waterSummary.tankerKL} KL`} />
                  <ReportRow label="Tanker cost" value={`₹${waterSummary.tankerCost.toLocaleString()}`} />
                </dl>
              )}
          </CardContent>
        </Card>

        {/* Power */}
        <Card>
          <CardHeader>
            <CardTitle className="text-sm" style={{ color: "#854F0B" }}>Power</CardTitle>
          </CardHeader>
          <CardContent>
            {!powerSummary
              ? <p className="text-sm text-muted-foreground">Loading…</p>
              : (
                <dl className="space-y-2 text-sm">
                  <ReportRow label="Total consumption" value={`${powerSummary.totalConsumptionKWH} kWh`} />
                  <ReportRow label="Outages" value={String(powerSummary.outageCount)} />
                  <ReportRow label="Outage hours" value={`${powerSummary.totalOutageHrs.toFixed(1)} h`} />
                  <ReportRow label="Diesel used" value={`${powerSummary.totalDieselUsedL.toFixed(1)} L`} />
                </dl>
              )}
          </CardContent>
        </Card>

        {/* Gas */}
        <Card>
          <CardHeader>
            <CardTitle className="text-sm" style={{ color: "#0F6E56" }}>Gas</CardTitle>
          </CardHeader>
          <CardContent>
            {!gasSummary
              ? <p className="text-sm text-muted-foreground">Loading…</p>
              : (
                <dl className="space-y-2 text-sm">
                  <ReportRow label="Total consumption" value={`${gasSummary.totalConsumptionSCM} SCM`} />
                  <ReportRow label="Avg pressure" value={`${gasSummary.avgPressurePSI} PSI`} />
                  <ReportRow label="Readings" value={String(gasSummary.readings)} />
                  <ReportRow label="Last meter" value={String(gasSummary.lastMeterReading)} />
                </dl>
              )}
          </CardContent>
        </Card>

        {/* Sewage */}
        <Card>
          <CardHeader>
            <CardTitle className="text-sm" style={{ color: "#993C1D" }}>Sewage / STP</CardTitle>
          </CardHeader>
          <CardContent>
            {!sewageSummary
              ? <p className="text-sm text-muted-foreground">Loading…</p>
              : (
                <dl className="space-y-2 text-sm">
                  <ReportRow label="Readings logged" value={String(sewageSummary.readings)} />
                  <ReportRow label="Normal uptime" value={`${sewageSummary.uptimePct}%`} />
                  <ReportRow label="Avg sludge level" value={`${sewageSummary.avgSludgePct}%`} />
                </dl>
              )}
          </CardContent>
        </Card>

        {/* Waste */}
        <Card>
          <CardHeader>
            <CardTitle className="text-sm" style={{ color: "#993556" }}>Waste</CardTitle>
          </CardHeader>
          <CardContent>
            {!wasteSummary
              ? <p className="text-sm text-muted-foreground">Loading…</p>
              : (
                <dl className="space-y-2 text-sm">
                  <ReportRow label="Total waste" value={`${wasteSummary.totalKG} KG`} />
                  <ReportRow label="Dry waste" value={`${wasteSummary.dryKG} KG`} />
                  <ReportRow label="Wet waste" value={`${wasteSummary.wetKG} KG`} />
                  <ReportRow label="Segregation" value={`${wasteSummary.segregationCompliance}%`} />
                </dl>
              )}
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

function ReportRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between">
      <dt className="text-muted-foreground">{label}</dt>
      <dd className="font-medium">{value}</dd>
    </div>
  );
}
