"use client";

import { useState } from "react";
import { useAction } from "convex/react";
import { api } from "@/convex/_generated/api";
import { FileDown, Loader2 } from "lucide-react";
import { Button } from "./button";
import { toast } from "sonner";

interface PdfReportButtonProps {
  societyId: string;
  blockId: string;
  societyName: string;
}

export function PdfReportButton({ societyId, blockId, societyName }: PdfReportButtonProps) {
  const [loading, setLoading] = useState(false);
  const generateReport = useAction(api.reports.generateMonthlyReport);

  async function handleDownload() {
    setLoading(true);
    toast.info("Generating AI report… this takes 10–15 seconds");
    try {
      const data = await generateReport({ societyId: societyId as any, blockId: blockId as any });
      await buildAndDownloadPdf(data, societyName);
      toast.success("Report downloaded");
    } catch (e: any) {
      toast.error("Report failed: " + (e.message ?? "unknown"));
    } finally {
      setLoading(false);
    }
  }

  return (
    <Button size="sm" variant="outline" onClick={handleDownload} disabled={loading} className="gap-1.5">
      {loading ? <Loader2 className="h-3.5 w-3.5 animate-spin" /> : <FileDown className="h-3.5 w-3.5" />}
      {loading ? "Generating…" : "AI Monthly Report"}
    </Button>
  );
}

async function buildAndDownloadPdf(data: any, societyName: string) {
  // Dynamic import so jspdf doesn't inflate initial bundle
  const { default: jsPDF } = await import("jspdf");
  const { default: autoTable } = await import("jspdf-autotable");

  const doc = new jsPDF({ orientation: "portrait", unit: "mm", format: "a4" });
  const pageW = doc.internal.pageSize.getWidth();
  const margin = 18;
  let y = 20;

  // ── Header ──
  doc.setFillColor(15, 23, 42);
  doc.rect(0, 0, pageW, 35, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(16);
  doc.setFont("helvetica", "bold");
  doc.text("BlockSense AI", margin, 15);
  doc.setFontSize(10);
  doc.setFont("helvetica", "normal");
  doc.text("Monthly Utility & Management Report", margin, 22);
  doc.setFontSize(9);
  doc.text(`${data.society?.name ?? societyName}  ·  ${data.block?.name ?? ""}  ·  ${data.month}`, margin, 29);
  doc.setTextColor(0, 0, 0);
  y = 45;

  // ── AI Narrative ──
  doc.setFillColor(245, 240, 255);
  doc.roundedRect(margin, y, pageW - margin * 2, 4, 1, 1, "F");
  doc.setFontSize(9);
  doc.setFont("helvetica", "bold");
  doc.setTextColor(88, 28, 135);
  doc.text("✦ AI Executive Summary", margin + 3, y + 3);
  doc.setTextColor(0, 0, 0);
  y += 8;

  doc.setFont("helvetica", "normal");
  doc.setFontSize(9);
  const narrativeLines = doc.splitTextToSize(data.narrative ?? "No narrative available.", pageW - margin * 2);
  doc.text(narrativeLines, margin, y);
  y += narrativeLines.length * 5 + 6;

  // ── KPI table ──
  doc.setFont("helvetica", "bold");
  doc.setFontSize(10);
  doc.text("Key Performance Indicators", margin, y);
  y += 4;

  autoTable(doc, {
    startY: y,
    margin: { left: margin, right: margin },
    head: [["Metric", "This Month", "Status"]],
    body: [
      ["Water Consumption", `${data.water.totalKL} KL`, data.water.totalKL > 0 ? "✓ Data available" : "— No data"],
      ["Power Consumption", `${data.power.totalKWH} kWh`, data.power.totalKWH > 0 ? "✓ Data available" : "— No data"],
      ["Maintenance Collected", `₹${data.payments.collected.toLocaleString("en-IN")}`, data.payments.collected > 0 ? "✓ Good" : "— Nil"],
      ["Outstanding Dues", `₹${data.payments.outstanding.toLocaleString("en-IN")}`, data.payments.defaulters > 0 ? `⚠ ${data.payments.defaulters} defaulters` : "✓ All clear"],
      ["Alerts Triggered", `${data.alerts.total}`, data.alerts.critical > 0 ? `⚠ ${data.alerts.critical} critical` : "✓ No critical"],
      ["Service Requests", `${data.serviceRequests.total}`, data.serviceRequests.open > 0 ? `${data.serviceRequests.open} open` : "✓ All resolved"],
    ],
    headStyles: { fillColor: [15, 23, 42], textColor: 255, fontSize: 9 },
    bodyStyles: { fontSize: 9 },
    alternateRowStyles: { fillColor: [248, 250, 252] },
    theme: "striped",
  });

  y = (doc as any).lastAutoTable.finalY + 10;

  // ── Footer ──
  const footerY = doc.internal.pageSize.getHeight() - 12;
  doc.setFillColor(15, 23, 42);
  doc.rect(0, footerY - 4, pageW, 16, "F");
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(8);
  doc.text(
    `Generated by BlockSense AI  ·  ${new Date(data.generatedAt).toLocaleString("en-IN")}  ·  Confidential`,
    pageW / 2,
    footerY + 4,
    { align: "center" }
  );

  doc.save(`BlockSense_Report_${data.month?.replace(" ", "_")}.pdf`);
}
